name: Main Workflow

on:
  push:
    branches: [ master ]

jobs:
  build_docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/doxygen/doxygen:latest

    permissions:
      contents: write

    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v5

      - name: Generate Documentation
        run: doxygen > doxygen.log 2>&1 | tee doxygen.log

      - name: Upload Doxygen Log
        uses: actions/upload-artifact@v7
        with:
          name: doxygen-log
          path: doxygen.log
          archive: false

      - name: Upload Documentation
        uses: actions/upload-artifact@v7
        with:
          name: Documentation
          path: docs/


  deploy_docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build_docs

    permissions:
      contents: write

    steps:
      - name: Download Documentation
        uses: actions/download-artifact@v8
        with:
          name: Documentation
          path: docs/

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html
          commit_message: ${{ github.event.head_commit.message }}
          publish_branch: docs
          enable_jekyll: false
