name: Main Workflow

# TODO: Generate diffs here too

on:
  push:
    branches: [ master ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Build Documentation
        run: doxygen > doxygen.log 2>&1 | tee doxygen.log

      - name: Upload Doxygen Log Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Doxygen Log Artifact
          path: doxygen.log

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          commit_message: ${{ github.event.head_commit.message }}
          publish_dir: docs/html
          publish_branch: docs
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: false
